-- Step 1: Classify 3000 RAW_TRANSCRIPTS using AI_CLASSIFY 
-- 4:31 on an X-Small warehouse | Query ID 01c3bb80-0001-548c-0016-cdcf007dd166 | 
CREATE OR REPLACE TABLE FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_CLASSIFY_PREDICTIONS AS
SELECT
    TRANSCRIPT_ID,
    TRANSCRIPT,
    CATEGORY AS ACTUAL_CATEGORY,
    SNOWFLAKE.CORTEX.AI_CLASSIFY(
        TRANSCRIPT,
        ['Billing', 'Technical Support', 'Account Management', 'Product Inquiry', 'Complaint', 'Cancellation']
    ) AS AI_CLASSIFY_RESULT
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.RAW_TRANSCRIPTS;FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_CLASSIFY_PREDICTIONS

-- Step 2: Overall accuracy
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN ACTUAL_CATEGORY = AI_CLASSIFY_RESULT:labels[0]::STRING THEN 1 ELSE 0 END) AS correct,
    ROUND(correct / total_rows * 100, 1) AS accuracy_pct
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_CLASSIFY_PREDICTIONS;

-- Step 3: Per-category accuracy
SELECT
    ACTUAL_CATEGORY,
    COUNT(*) AS total,
    SUM(CASE WHEN ACTUAL_CATEGORY = AI_CLASSIFY_RESULT:labels[0]::STRING THEN 1 ELSE 0 END) AS correct,
    ROUND(correct / total * 100, 1) AS accuracy_pct
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_CLASSIFY_PREDICTIONS
GROUP BY ACTUAL_CATEGORY
ORDER BY accuracy_pct;

-- Step 4: Show misclassifications
SELECT
    TRANSCRIPT_ID,
    ACTUAL_CATEGORY,
    AI_CLASSIFY_RESULT:labels[0]::STRING AS PREDICTED_CATEGORY,
    LEFT(TRANSCRIPT, 200) AS TRANSCRIPT_PREVIEW
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_CLASSIFY_PREDICTIONS
WHERE ACTUAL_CATEGORY != AI_CLASSIFY_RESULT:labels[0]::STRING
ORDER BY ACTUAL_CATEGORY;