-- Step 1: Run inference on all transcripts
-- 19s
CREATE OR REPLACE TABLE FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_COMPLETE_PREDICTIONS AS
SELECT
    TRANSCRIPT_ID,
    TRANSCRIPT,
    CATEGORY AS ACTUAL_CATEGORY,
    TRIM(SNOWFLAKE.CORTEX.COMPLETE(
        'FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.CUSTOMER_SERVICE_CLASSIFIER',
        'Classify the following customer service call transcript into exactly one of these categories: Billing, Technical Support, Account Management, Product Inquiry, Complaint, Cancellation.\n\nTranscript:\n' || TRANSCRIPT
    )) AS AI_COMPLETE_PREDICTIONS
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.RAW_TRANSCRIPTS;

-- Step 2: Overall accuracy
SELECT
    COUNT(*) AS total_rows,
    SUM(CASE WHEN ACTUAL_CATEGORY = AI_COMPLETE_PREDICTIONS THEN 1 ELSE 0 END) AS correct,
    ROUND(correct / total_rows * 100, 1) AS accuracy_pct
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_COMPLETE_PREDICTIONS;

-- Step 3: Per-category accuracy
SELECT
    ACTUAL_CATEGORY,
    COUNT(*) AS total,
    SUM(CASE WHEN ACTUAL_CATEGORY = AI_COMPLETE_PREDICTIONS THEN 1 ELSE 0 END) AS correct,
    ROUND(correct / total * 100, 1) AS accuracy_pct
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_COMPLETE_PREDICTIONS
GROUP BY ACTUAL_CATEGORY
ORDER BY accuracy_pct;

-- Step 4: Show any misclassifications
SELECT
    TRANSCRIPT_ID,
    ACTUAL_CATEGORY,
    AI_COMPLETE_PREDICTIONS,
    LEFT(TRANSCRIPT, 200) AS TRANSCRIPT_PREVIEW
FROM FINETUNING_AI_COMPLETE.CALL_TRANSCRIPTS.AI_COMPLETE_PREDICTIONS
WHERE ACTUAL_CATEGORY != AI_COMPLETE_PREDICTIONS
ORDER BY ACTUAL_CATEGORY;
